### ISSUE TITLE
Please solve my problem. It's important

### ISSUE THREAD

**Issue by Unayes09** [JubaerHossain/zk-jubaer#2]
its not working and shows the error below..
ok tcp
Promise Rejected
c:\node-zklib\node_modules\zk-jubaer\src\jtcp.js:246
const header = decodeTCPHeader(reply.subarray(0, 16))
^

TypeError: Cannot read properties of undefined (reading 'subarray')
at c:\node-zklib\node_modules\zk-jubaer\src\jtcp.js:246:44

Node.js v21.1.0

here the reply is null.what can i do?If any other settings required tell me. I give my ip adress which is connected with my device and it's also connected with zkteco software.

**Comment by shanto2007** [comment]
Same problem for me please help

**Comment by JubaerHossain** [comment]
which method ?

**Comment by aqibbangash** [comment]
@JubaerHossain While running your sample code, the device connects but on getAttendances function, this error comes up. These are my logs

```
initiating...
ZKJUBAER ZKJUBAER {
  connectionType: null,
  jtcp: JTCP {
    ip: '192.168.18.201',
    port: 4370,
    timeout: 5200,
    sessionId: null,
    replyId: 0,
    socket: null
  },
  judp: JUDP {
    ip: '192.168.18.201',
    port: 4370,
    timeout: 5200,
    socket: null,
    sessionId: null,
    replyId: 0,
    inport: 5000
  },
  interval: null,
  timer: null,
  isBusy: false,
  ip: '192.168.18.201'
}
creating socket...
ok tcp
getting attendances...
Promise Rejected
/Volumes/Official/source-code/zkt/node_modules/zk-jubaer/src/jtcp.js:246
      const header = decodeTCPHeader(reply.subarray(0, 16))
                                           ^

TypeError: Cannot read properties of undefined (reading 'subarray')
    at /Volumes/Official/source-code/zkt/node_modules/zk-jubaer/src/jtcp.js:246:44

Node.js v20.7.0
```

**Comment by aqibbangash** [comment]
Basically, the response Header commandId is coming in to be 2005 (CMD_ACK_UNAUTH) where as the expected commandId is 1501 (CMD_DATA)

Any idea why this is happening?

**Comment by Unayes09** [comment]
@aqibbangash @JubaerHossain can you solve the problem?
ok tcp
Promise Rejected
f:\zkteco\zk-jubaer\src\jtcp.js:246
      const header = decodeTCPHeader(reply.subarray(0, 16))
                                           ^

TypeError: Cannot read properties of undefined (reading 'subarray')
    at f:\zkteco\zk-jubaer\src\jtcp.js:246:44

Node.js v21.1.0
this type of error showing to me actually

**Comment by Sistemas-UPE** [comment]
Hi, i start work for this and me too have this problem.
I am working to acquire the registration reports for an access control and attendance model SpeedFace-V5L from the zkteco brand. I have another K20 model device and the code works perfectly, it can recover information about the device, user, and most importantly the attendance records, but when trying the same on the SpeedFace-V5L it recovers information about the device, users, but not the sold records. . Already review the structure of the library and it is very simple, there is a function that is responsible for reading all the outputs of the socket after connecting to the device. This connection collects all the available elements, as follows:

requestData(msg) {
    return new Promise((resolve, reject) => {
      let timer = null
      let replyBuffer = Buffer.from([])
      const internalCallback = (data) => {
        this.socket.removeListener('data', handleOnData)
        timer && clearTimeout(timer)
        resolve(data)
      }

      const handleOnData = (data) => {
        replyBuffer = Buffer.concat([replyBuffer, data])
        if (checkNotEventTCP(data)) return;
        clearTimeout(timer)   

        const header = decodeTCPHeader(replyBuffer.subarray(0,16));

        if(header.commandId === COMMANDS.CMD_DATA){
          timer = setTimeout(()=>{
            internalCallback(replyBuffer)
          }, 1000)
        }else{
          timer = setTimeout(() => {
            reject(new Error('TIMEOUT_ON_RECEIVING_REQUEST_DATA'))
          }, this.timeout)

          const packetLength = data.readUIntLE(4, 2)
          if (packetLength > 8) {
            internalCallback(data)
          }
        }
      }

the variable responseBuffer = Buffer.concat([replyBuffer, data]) is responsible for storing available elements that the socket throws through the buffer into an array, when debugging the contestBuffer array of the k20 device it contains 27 elements, while the device SpeedFace- V5L only selects 16, the curious thing here is that when pairing selects the elements under the 'data' statement that is declared in:
const internalCallback = (data) => {
        this.socket.removeListener('data', handleOnData)
        timer && clearTimeout(timer)
        resolve (data)
      }
My theory is that it must be identified if another keyword or something else is required for the new equipment that can help me identify or know what is required to consult the registration data, since it is very clear that it marks the error. which refers to an unestablished stay. only opting for 16 elements when in the previous equipment you opt for 27 elements, in the same way and if it helps anyone, I share the API Development Manual:
AMTMultiBio SDK For Windows which is the official zkteco manual
https://new-website-file.s3.ap-southeast-1.amazonaws.com/files/20230313/Armatura%20SDK%20Guide_MultiBio%202.1_Windows-202206.pdf

**Comment by Kireq1** [comment]
I am working to acquire the registration reports for an access control and attendance model SpeedFace-V5L from the zkteco brand. I have another K20 model device and the code works perfectly, it can recover information about the device, user, and most importantly the attendance records, but when trying the same on the SpeedFace-V5L it recovers information about the device, users, but not the sold records. . Already review the structure of the library and it is very simple, there is a function that is responsible for reading all the outputs of the socket after connecting to the device. This connection collects all the available elements, as follows:

the variable responseBuffer = Buffer.concat([replyBuffer, data]) is responsible for storing available elements that the socket throws through the buffer into an array, when debugging the contestBuffer array of the k20 device it contains 27 elements, while the device SpeedFace- V5L only selects 16, the curious thing here is that when pairing selects the elements under the 'data' statement that is declared in:
const internalCallback = (data) => {
        this.socket.removeListener('data', handleOnData)
        timer && clearTimeout(timer)
        resolve (data)
      }
My theory is that it must be identified if another keyword or something else is required for the new equipment that can help me identify or know what is required to consult the registration data, since it is very clear that it marks the error. which refers to an unestablished stay. only opting for 16 elements when in the previous equipment you opt for 27 elements, in the same way and if it helps anyone, I share the API Development Manual:
AMTMultiBio SDK For Windows which is the official zkteco manual

https://new-website-file.s3.ap-southeast-1.amazonaws.com/files/20230313/Armatura%20SDK%20Guide_MultiBio%202.1_Windows-202206.pdf

**Comment by Kireq1** [comment]
I am working to acquire the registration reports for an access control and attendance model SpeedFace-V5L from the zkteco brand. I have another K20 model device and the code works perfectly, it can recover information about the device, user, and most importantly the attendance records, but when trying the same on the SpeedFace-V5L it recovers information about the device, users, but not the sold records. . Already review the structure of the library and it is very simple, there is a function that is responsible for reading all the outputs of the socket after connecting to the device. This connection collects all the available elements, as follows:

requestData(msg) {
    return new Promise((resolve, reject) => {
      let timer = null
      let replyBuffer = Buffer.from([])
      const internalCallback = (data) => {
        this.socket.removeListener('data', handleOnData)
        timer && clearTimeout(timer)
        resolve(data)
      }

      const handleOnData = (data) => {
        replyBuffer = Buffer.concat([replyBuffer, data])
        if (checkNotEventTCP(data)) return;
        clearTimeout(timer)   

        const header = decodeTCPHeader(replyBuffer.subarray(0,16));

        if(header.commandId === COMMANDS.CMD_DATA){
          timer = setTimeout(()=>{
            internalCallback(replyBuffer)
          }, 1000)
        }else{
          timer = setTimeout(() => {
            reject(new Error('TIMEOUT_ON_RECEIVING_REQUEST_DATA'))
          }, this.timeout)

          const packetLength = data.readUIntLE(4, 2)
          if (packetLength > 8) {
            internalCallback(data)
          }
        }
      }


the variable responseBuffer = Buffer.concat([replyBuffer, data]) is responsible for storing available elements that the socket throws through the buffer into an array, when debugging the contestBuffer array of the k20 device it contains 27 elements, while the device SpeedFace- V5L only selects 16, the curious thing here is that when pairing selects the elements under the 'data' statement that is declared in:
const internalCallback = (data) => {
        this.socket.removeListener('data', handleOnData)
        timer && clearTimeout(timer)
        resolve (data)
      }
My theory is that it must be identified if another keyword or something else is required for the new equipment that can help me identify or know what is required to consult the registration data, since it is very clear that it marks the error. which refers to an unestablished stay. only opting for 16 elements when in the previous equipment you opt for 27 elements, in the same way and if it helps anyone, I share the API Development Manual:
AMTMultiBio SDK For Windows which is the official zkteco manual:
https://new-website-file.s3.ap-southeast-1.amazonaws.com/files/20230313/Armatura%20SDK%20Guide_MultiBio%202.1_Windows-202206.pdf

**Comment by Makiesse** [comment]
estou trabalhando com SpeedFaceV5L mais tive alguns problemas com resposta quando busco o registro de ponto.`	

"data": [

		{
			"userSn": 1,
			"deviceUserId": "1",
			"recordTime": "Thu Jul 17 2025 09:21:43 GMT+0100 (Hora padrão da África Ocidental)",
			"ip": "192.168.188.2"
		},
		{
			"userSn": 13055,
			"deviceUserId": "55",
			"recordTime": "Sat Jan 01 2000 00:00:00 GMT+0100 (Hora padrão da África Ocidental)",
			"ip": "192.168.188.2"
		},
		{
			"userSn": 255,
			"deviceUserId": "",
			"recordTime": "Sat Jan 01 2000 00:00:00 GMT+0100 (Hora padrão da África Ocidental)",
			"ip": "192.168.188.2"
		},
		{
			"userSn": 0,
			"deviceUserId": "",
			"recordTime": "Tue Feb 08 2000 16:25:40 GMT+0100 (Hora padrão da África Ocidental)",
			"ip": "192.168.188.2"
		},
		{
			"userSn": 0,
			"deviceUserId": "",
			"recordTime": "Sat Oct 09 2027 22:21:51 GMT+0100 (Hora padrão da África Ocidental)",
			"ip": "192.168.188.2"
		},`

as datas das picagem estão estranhas, alguns dados em falta tipo o userSn. Tem como resolver isso?
